branchName: '${issue.number}'
defaultBranch: 'develop'
branches:
  - label: 'hotfix'
    prefix: 'hotfix/'

  - label: 'feature'
    prefix: 'feature/'
    
  - label: 'docs'
    prefix: 'docs/'

  - label: 'test'
    prefix: 'test/'

  - label: 'fix'
    prefix: 'fix/'

  - label: 'enhancement'
    prefix: 'enhancement/'
sourceBranch:
  - label: 'hotfix'
    name: 'main'
  - label: 'bug'
    name: 'develop'
  - labal: '*'
    name: 'develop'
    
commentMessage: '🌱 브랜치 `${branchName}`가 생성되었습니다. 이슈: ${issue.title}'
openDraftPR: false
autoCloseIssue: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueMilestoneToPR: true
