spring:
  # 데이터베이스 연결 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8.x용 Dialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
     mode: never

  # Redis 연결 설정
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  batch:
    jdbc:
      initialize-schema: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html # 스웨거 접근 경로
  api-docs:
    path: /api-docs # openAPI 접근 경로. default 값은 /v3/api-docs 이다.
  show-actuator: true # Spring Actuator의 endpoint까지 보여줄 것인지?
  default-consumes-media-type: application/json # request media type 의 기본 값
  default-produces-media-type: application/json # response media type 의 기본 값
  paths-to-match: # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.
    - /api/v1/**

jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: ${JWT_SECRET}
  access-token-header: Authorization
  access-token-validity-in-hour: 3
  refresh-token-cookie: code-mate-ref
  refresh-token-expiration-days: 60
  redis:
    key:
      prefix: programmer
      suffix: token_rts
ranking:
  daily: daily
  key: ranking
